name: build

on:
  push:
  workflow_dispatch:

env:
  github_token: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: mingw64, arch: x86_64 }
        ]
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-${{ matrix.arch }}-gcc
          make
          libtool
          autoconf
          automake-wrapper
          mingw-w64-${{ matrix.arch }}-github-cli

    - name: prepare environment
      run: |
        echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
        git config --global core.autocrlf false

    - name: fetch libplist
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: libplist-latest_${{ matrix.arch }}-${{ matrix.msystem }}
        repo: libimobiledevice/libplist

    - name: fetch libusbmuxd
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: libusbmuxd-latest_${{ matrix.arch }}-${{ matrix.msystem }}
        repo: libimobiledevice/libusbmuxd

    - name: fetch libimobiledevice-glue
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: libimobiledevice-glue-latest_${{ matrix.arch }}-${{ matrix.msystem }}
        repo: libimobiledevice/libimobiledevice-glue

    - name: install external dependencies
      run: |
        mkdir extract
        for I in *.tar; do
          tar -C extract -xvf $I
        done
        cp -r extract/* /

    - uses: actions/checkout@v2
    - name: autogen and make install
      run: |
        ./autogen.sh CC=gcc CXX=g++ --enable-debug
        make -j install

    - name: prepare release
      run: |
        mkdir -p rel
        make -j install
        # Grab idevicesyslog.exe and deps
        find /mingw64/bin/ -type f \( -name "idevicesyslog.exe" -o \
                                      -name "libimobiledevice-1.0.dll" -o \
                                      -name "libplist-2.0.dll" -o \
                                      -name "libusbmuxd-2.0.dll" -o \
                                      -name "libimobiledevice-glue-1.0.dll" -o \
                                      -name "libcrypto-3-x64.dll" -o \
                                      -name "libssl-3-x64.dll" \) \
                                      -exec cp -v {} rel \;
        tar -C rel -cJvf idevicesyslog-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz .

    - name: publish release
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"
        gh release upload "$TAG" idevicesyslog-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz
